### ISSUE TITLE
Inclusion of Lainchan and Arisuchan

### ISSUE THREAD

**Issue by DonaldTsang** [catamphetamine/captchan#3]
Two of the best programming boards, might be a good idea to include them

**Comment by catamphetamine** [comment]
Are they still alive?

**Comment by DonaldTsang** [comment]
Alive but slow

**Comment by catamphetamine** [comment]
Well, ok, `lainchan` is based on `vichan` which is already supported, so adding it would be easy.

For the logo, I liked this one:

![https://res.cloudinary.com/teepublic/image/private/s--p-AsvNG_--/t_Preview/b_rgb:ffffff,c_limit,f_jpg,h_630,q_90,w_630/v1517037595/production/designs/2313180_0.jpg](https://res.cloudinary.com/teepublic/image/private/s--p-AsvNG_--/t_Preview/b_rgb:ffffff,c_limit,f_jpg,h_630,q_90,w_630/v1517037595/production/designs/2313180_0.jpg)

But it's too big in `kB`, so I chose another one:

![icon](https://user-images.githubusercontent.com/477167/61508431-7f093380-a9f2-11e9-916e-be2de2b8ea68.png)

Seems to be working:

![image](https://user-images.githubusercontent.com/477167/61508110-29805700-a9f1-11e9-8c7c-e94e79d65f28.png)

![image](https://user-images.githubusercontent.com/477167/61508426-74e73500-a9f2-11e9-9ec4-768e9c8d71c2.png)

It won't be deployed yet though because the repo is currently being refactored.
Maybe somewhere in August, when the refactoring has finished.

**Comment by catamphetamine** [comment]
Added `arisuchan`.

![image](https://user-images.githubusercontent.com/477167/61519357-66aa1080-aa14-11e9-983b-88f29ab452d9.png)

**Comment by DonaldTsang** [comment]
Thanks!

**Comment by catamphetamine** [comment]
FYI: redeployed

https://catamphetamine.github.io/captchan/?chan=lainchan
https://catamphetamine.github.io/captchan/?chan=arisuchan

No code syntax highlighting

**Comment by DonaldTsang** [comment]
> No code syntax highlighting
Well that would be bad for 8/tech/ as well

**Comment by catamphetamine** [comment]
@DonaldTsang see https://github.com/catamphetamine/captchan/issues/4

**Comment by DonaldTsang** [comment]
API documentation?

**Comment by catamphetamine** [comment]
What do you mean?

**Comment by DonaldTsang** [comment]
@catamphetamine are there any API documentation for Lainchan and Arisuchan? If not would it be useful to make one?

**Comment by catamphetamine** [comment]
@DonaldTsang I see. Updated the readme.
